version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: "Branch"
          command: echo ${CIRCLE_BRANCH}

      - run:
          name: Install Firebase
          command: sudo yarn global add firebase-tools
      - run:
          command: yarn build

      - deploy:
          name: Deploy & Alias
          command: |
                firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
